name: build-windows

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

# لازم برای ساخت/به‌روزرسانی Release
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Enable long paths (Windows)
        run: git config --system core.longpaths true

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build
        run: |
          python -m PyInstaller --noconsole --onefile dns_switcher.py

      - name: Upload artifact
      # نام آرتیفکت با ref (tag/branch) ذخیره می‌شود
        uses: actions/upload-artifact@v4
        with:
          name: dns_switcher-windows-${{ github.ref_name }}
          path: dist/dns_switcher.exe

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dns_switcher-windows-${{ github.ref_name }}
          path: ./dist

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/dns_switcher.exe
          generate_release_notes: true
